#!/bin/bash
set -euo pipefail

CUDA_DEVICE_IDX=6 \
POST_TRAIN_BENCH_AGENT=ml_master \
POST_TRAIN_BENCH_AGENT_CONFIG=gpt-5.5 \
POST_TRAIN_BENCH_REQUIRED_GPU_NAME=H20 \
POST_TRAIN_BENCH_EXPERIMENT_NAME=_prompt1_gpu6_ml_master_htcondor \
POST_TRAIN_BENCH_PROMPT=prompt1 \
POST_TRAIN_BENCH_JUDGE_PROMPT=prompt \
POST_TRAIN_BENCH_JUDGE_MODEL=gpt-5.5 \
ML_MASTER_STEPS=24 \
ML_MASTER_PARALLEL_SEARCH_NUM=1 \
CONDOR_GPU_REQUIREMENTS=true \
bash scripts/submit_codex_personal_htcondor.sh
