#!/bin/bash
set -euo pipefail

CUDA_DEVICE_IDX=5 \
POST_TRAIN_BENCH_REQUIRED_GPU_NAME=H20 \
POST_TRAIN_BENCH_EXPERIMENT_NAME=_prompt3_gpu5_htcondor \
POST_TRAIN_BENCH_PROMPT=prompt3 \
POST_TRAIN_BENCH_JUDGE_PROMPT=prompt \
POST_TRAIN_BENCH_JUDGE_MODEL=gpt-5.5 \
POST_TRAIN_BENCH_COPY_HOST_CODEX_AUTH=1 \
POST_TRAIN_BENCH_INSTALL_HOST_CODEX_BINARY=1 \
CONDOR_GPU_REQUIREMENTS=true \
bash scripts/submit_codex_personal_htcondor.sh
